css/style.css: >
  .wraper {
    display: block;
    width: auto;
    height: auto;
  }
js/script.js: >
index.html: >
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <title>EXAMPLE TITLE</title>
      <!-- Bootstrap -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <!-- JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <!-- Custom CSS -->
       <link rel="stylesheet" type="text/css" href="css/style.css">
      <!-- Custom JS -->
       <script src="js/script.js"></script>
    </head>
    <body>
      <div class="wraper">
        <div class="header"></div>
        <div class="main">
          <div class="sidebar"></div>
          <div class="content"></div>
          <div class="a-sidebar"></div>
        </div>
        <div class="footer"></div>
      </div>
    </body>
  </html>
